language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO="Django>=1.11,<1.12"
  - DJANGO="Django>=2.0,<2.1"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $DJANGO
  - pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source cruds runtests.py

# report coverage to coveralls.io
after_success: coveralls
matrix:
  exclude:
    - python: "2.7"
      env: DJANGO="Django>=2.0,<2.1"
